services:
  - type: web
    name: fastapi-drive-upload
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn fastapi_drive_upload:app --host 0.0.0.0 --port 10000
    plan: free
    envVars:
      - key: PORT
        value: 10000
